### ISSUE TITLE
The program keeps reporting 400 errors

### ISSUE THREAD

**Issue by 13066264851** [aws-samples/aws-ocpp-gateway#116]
Hi，

When I changed the log level of the program to INFO, the program continued to output 400 errors. But no requests were actually made to access the server, and the errors were very frequent, close to once a second.

<img width="1733" alt="image" src="https://github.com/aws-samples/aws-ocpp-gateway/assets/47441647/a0ed2943-e24f-482f-bc1e-33ae7ae1727f">

Thanks

**Comment by galinsky** [comment]
I believe this is related to the load balancer health check. Checks are coming from multiple AZs. Per the cdl (can be readily changed) the check is being initiated every 10s. It's checking only for tcp connection which the Websocket server is complaining about. This could be improved, but should not be an issue.

**Comment by 13066264851** [comment]
@galinsky  However, I changed the period of the health check to 300s, and the corresponding error report remained unchanged
