### ISSUE TITLE
What version of OCPP complaint stack is supported?

### ISSUE THREAD

**Issue by Bhuvi-Naveen** [aws-samples/aws-ocpp-gateway#39]
Dear @bigadsoleiman 

Does the OCPP complaint Gateway on AWS IOT core supports OCPP  version 1.6J or it is restricted to Ocpp 2.0/2.0.1 ? please advise.

Regards,
Bhuvi-Naveen

**Comment by galinsky** [comment]
It supports both 1.6J and 2.0.x versions of OCPP.

**Comment by Bhuvi-Naveen** [comment]
Hi @galinsky,

Thanks for the confirmation.

regards,
Bhuvi-Naveen
