### ISSUE TITLE
No module named RDPS

### ISSUE THREAD

**Issue by BlomJanou** [aws-samples/aws-ocpp-gateway#56]
I tried to simulate a CP in **Simulating CP connectivity step 9**.
When running python3 simulate.py --url {websocket URL generated from the AWS OCPP Stack} --cp-id CP1 I get:
ERROR:root:VirtualChargePoint1: Waited 30s for response on .......

It turns out there is a missing import in the lambda function called: AwsOcppGatewayStack-OCPPMessageProcessor....
[ERROR] Runtime.ImportModuleError: Unable to import module 'message_processor': No module named 'rpds.rpds'

I tried adding rpds to the requirements.txt file and deploying it trough AWS, but it did not resolve the issue.

**Comment by galinsky** [comment]
@BlomJanou there's no dependency on a `rpds` package. Can you share the specific error the Lambda function is generating?

**Comment by jb-cw** [comment]
It's happening with the latest version of aws-ocpp-gateway, the simulator
hangs up and is unable to connect with the gateway. Here's a screenshot
from cloudwatch log and simulator output.

*Simulator Output*:
INFO:ocpp:CP1: send
[2,"a5984f53-bacd-4a49-89e6-24f60844f763","BootNotification",{"chargingStation":{"serialNumber":"CP1234567890A01","model":"CHARGE_POINT_MODEL","vendorName":"CHARGE_POINT_VENDOR","firmwareVersion":"1.2.3.4","modem":{"iccid":"891004234814455936F","imsi":"310410123456789"}},"reason":"PowerUp"}]
ERROR:root:CP1: Waited 30s for response on
[2,"a5984f53-bacd-4a49-89e6-24f60844f763","BootNotification",{"chargingStation":{"serialNumber":"CP1234567890A01","model":"CHARGE_POINT_MODEL","vendorName":"CHARGE_POINT_VENDOR","firmwareVersion":"1.2.3.4","modem":{"iccid":"891004234814455936F","imsi":"310410123456789"}},"reason":"PowerUp"}].

*Lambda logs from Cloudwatch*:
[image: image.png]

**Comment by galinsky** [comment]
I'm still unclear where the reference to `rpds` comes from. Can you include your Lambda function, I want to see where this is being referenced.

**Comment by jb-cw** [comment]
The Lambda function is code for message_processor here https://github.com/aws-samples/aws-ocpp-gateway/blob/main/src/ocpp-message-processor/message_processor.py

I haven't made any changes to this function and logs with rpds error are from message_processor function.

I've experienced this issue separately from @BlomJanou.

**Comment by jb-cw** [comment]
If it makes any difference, I've executed npx cdk deploy and destroy multiple times and cloned a new repo each time deploying it to AWS.

**Comment by jb-cw** [comment]
Could this be related in any way? https://github.com/aws/aws-cdk/issues/26300

**Comment by BernardVas** [comment]
Hello, 
Same problem here.
I'm keeping jsonschema==4.17.3 to avoid the error.
I hope this will be resolved

**Comment by jb-cw** [comment]
@BernardVas how're you keeping it to jsonschema===4.17.3? Where can we specify it?

**Comment by galinsky** [comment]
@jb-cw I'm testing this right now; setting:

```
jsonschema==4.17.3
```

in `src/ocpp-message-processor/requirements.txt` should do it

**Comment by jb-cw** [comment]
@galinsky thank you so much!

**Comment by galinsky** [comment]
https://github.com/aws-samples/aws-ocpp-gateway/commit/1918005823ed28c84afc4ea62944b6a8d6483088

**Comment by galinsky** [comment]
@jb-cw please check out and validate with the most recent commit.

**Comment by jb-cw** [comment]
@galinsky it works with the latest commit. Really appreciate your help on this!
