### ISSUE TITLE
Deployment gets failed

### ISSUE THREAD

**Issue by sohaibbinmohsin** [aws-samples/aws-ocpp-gateway#79]
I am trying to deploy but every time stack fails while creating the ECS service. I am not getting an elaborative error. It just says resource timed out while waiting for completion.

`Error: Stack Deployments Failed: Error: The stack named AwsOcppGatewayStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource timed out waiting for completion `

Can someone please help?

**Comment by sohaibbinmohsin** [comment]
After debugging, I found out this was the error I was getting:
`./run-server.sh: cannot execute: required file not found`

Solution:
The issue was caused by incorrect line endings (CRLF) in the run-server.sh script. To resolve this, I manually converted the line endings from CRLF to LF (Unix format).

**Comment by tnahata** [comment]
Sohaib,
I am struggling with a similar error where my deployment just gets stuck! Would you be able to help me out with debugging the issue?
Thanks!
